name: "Network UPS Tools 2"
version: "0.2.0"
slug: "nut2"
description: "Zweites NUT-Add-on für eine zweite USV"
startup: services
boot: auto
host_network: true
init: false
privileged:
  - SYS_ADMIN
devices:
  - /dev/bus/usb:/dev/bus/usb
usb: true
arch:
  - amd64
  - armv7
  - aarch64
options:
  users:
    - username: "nutuser"
      password: "deinPasswort"
      instcmds:
        - all
      actions:
        - SET
        - FSD
  devices:
    - name: ups2
      driver: "usbhid-ups"
      port: "auto"
  mode: netserver
schema:
  users:
    - username: str
      password: str
      instcmds:
        - str
      actions:
        - str
  devices:
    - name: str
      driver: str
      port: str
  mode: list(netserver|standalone)
